export {
  type Channel,
  type DeclaredOf,
  type FailureOf,
  INTERNAL_FAILURE,
  type InternalFailure,
  type ChannelMap,
  type ClientApi,
  type Handlers,
  type ParamsOf,
  type ResultOf,
  channel,
} from './channel.js';
export {
  type ChannelId,
  type ChannelParams,
  type ChannelResult,
  type Channels,
  type ContractClient,
  type ContractHandlers,
  // Invariant L11's mechanism. Exported so a caller can size its reads under
  // the bound rather than discover it as a refusal.
  MAX_RANGE_BYTES,
  // The recent list's cap, RESTATED in `apps/desktop` because this package may
  // not import that one. Exported so the case that holds the two together has
  // something to compare against — without it the agreement is a sentence in
  // this file's comment and nothing else, which is what the audit of
  // `87540a5..HEAD` found it to be.
  MAX_RECENT_ENTRIES,
  // The text layer's two bounds. Exported because the caller that sizes a read
  // under the line limit is the renderer, and the per-line cap is what the
  // main-side reader passes to `textLayerOf` — a second spelling of either
  // would be the number this channel refuses on, written twice.
  MAX_RASTER_BYTES,
  MAX_RASTER_PIXELS,
  MAX_TEXT_LAYER_LINE,
  MAX_TEXT_LAYER_LINES,
  // NAMED BECAUSE THE KERNEL SEAM NOW READS IT TOO. ADR-0040's extension hands
  // a command's apply the outline as pre-read data, so this shape has a reader
  // that is not a channel; a second declaration there would be two of one thing.
  type OutlineEntry,
  outlineEntrySchema,
  // The dictionary set and its two bounds. The list is exported because BOTH
  // sides key a record on it — main's package map and the renderer's display
  // titles — which is what makes adding a language two compile errors rather
  // than a checklist.
  MAX_AFFIX_BYTES,
  MAX_DICTIONARY_BYTES,
  // The OCR language set's SCHEMA. The set itself moved to `schemas.ts` on
  // 2026-09-11 — `ocrPage`'s payload needs it and a command schema cannot import
  // `channels.ts` back — and is exported below, from where it now lives.
  ocrEngineSchema,
  ocrLanguageSchema,
  trocrSizeSchema,
  SPELLING_LANGUAGES,
  type SpellingLanguage,
  spellingLanguageSchema,
  channelIds,
  channels,
} from './channels.js';
export { createClient, wrapHandler, wrapHandlers } from './boundary.js';
export { BRIDGE_KEY, type MonsteraBridge } from './bridge.js';
export {
  ENGINE_HOST_FRAME_MAX_BYTES,
  ENGINE_HOST_MAX_IN_FLIGHT,
  HOST_CORRELATION_ID_MAX_CHARS,
  type HostRequest,
  type HostResponse,
  LARGEST_INTENT_PAYLOAD_BYTES,
  hostRequestSchema,
  hostResponseSchema,
} from './hostProtocol.js';
export {
  FRAME_HEADER_BYTES,
  FRAME_LENGTH_CEILING,
  FrameDecoder,
  type FrameViolation,
  encodeFrame,
} from './frame.js';
export { type Incident, IncidentLog, type IncidentSink } from './incident.js';
export {
  type AnnotationColour,
  type AnnotationDraft,
  type AnnotationKindName,
  type AnnotationPoint,
  type AnnotationRect,
  type BorderEffect,
  type LineEnding,
  annotationKindNameSchema,
  annotationPointSchema,
  borderEffectSchema,
  lineEndingSchema,
  MAX_POLYGON_POINTS,
  type Command,
  type CommandKind,
  type CommandOfKind,
  MAX_ANNOTATION_BORDER,
  MAX_ANNOTATION_FONT,
  LINK_SCHEMES,
  MAX_ANNOTATION_TEXT,
  MAX_LINK_URI,
  type AnnotationOpacity,
  type LinkTarget,
  type MeasureScale,
  type MeasureUnit,
  measurePerPointSchema,
  measureScaleSchema,
  measureUnitSchema,
  MIN_ANNOTATION_FONT,
  MAX_INK_POINTS,
  MAX_PAGE_COORDINATE,
  addAnnotationSchema,
  addLinkSchema,
  annotationColourSchema,
  annotationDraftSchema,
  annotationRectSchema,
  batesNumberPagesSchema,
  commandSchema,
  // EVERY MEMBER, not just the first. `rotatePagesSchema` was exported alone
  // because one caller wanted one schema; the engine host's channels need the
  // MuPDF-routed subset as a union of its own, and a subset cannot be built
  // from a union whose members are unreachable
  // ([ADR-0039](../../../docs/DECISIONS/0039-a-byte-image-writer-round-trips-the-live-session.md)).
  cropPagesSchema,
  deletePagesSchema,
  duplicatePageSchema,
  generateTocSchema,
  headerFooterPagesSchema,
  insertBlankPageSchema,
  MAX_IMAGE_BYTES,
  type RenderableCommand,
  insertImagePageSchema,
  mergeDocumentSchema,
  movePageSchema,
  type NamesAnAnnotation,
  type NamesAFormField,
  type NamesATextObject,
  type NamesASecondDocument,
  MAX_REPLACED_TEXT,
  MAX_TEXT_REPLACEMENTS,
  MAX_EDITED_OBJECTS,
  MAX_FIND_TEXT,
  MAX_OBJECT_SCALE,
  MIN_OBJECT_SCALE,
  replaceAllTextSchema,
  replaceTextObjectSchema,
  placePageObjectSchema,
  recolorPageObjectsSchema,
  deletePageObjectsSchema,
  promoteFormObjectsSchema,
  type FieldFill,
  type FormFieldKind,
  type CreatedField,
  createFormFieldSchema,
  createdFieldSchema,
  deleteFormFieldsSchema,
  fieldFillSchema,
  fillFormFieldSchema,
  flattenFormFieldsSchema,
  PDF_ENCRYPTIONS,
  PDF_PERMISSIONS,
  type PdfEncryption,
  type PdfPermission,
  setDocumentProtectionSchema,
  applyRedactionsSchema,
  markMatchesForRedactionSchema,
  sanitizeDocumentSchema,
  PDF_SANITIZE_PARTS,
  type PdfSanitizePart,
  MAX_REDACT_MATCHES_PER_PAGE,
  PDF_REDACT_COVERS,
  PDF_REDACT_IMAGES,
  type PdfRedactCover,
  type PdfRedactImages,
  type FormDataFormat,
  type FormDataImportFormat,
  formDataFormatSchema,
  formDataImportFormatSchema,
  formFieldKindSchema,
  importFormDataSchema,
  MAX_DELETED_FIELDS,
  MAX_FORM_DATA_BYTES,
  MAX_FIELD_NAME,
  MAX_FIELD_OPTION,
  MAX_FIELD_OPTIONS,
  MAX_FIELD_VALUE,
  placeAnnotationSchema,
  placeImageSchema,
  MAX_IMAGE_PAGES,
  removeAnnotationSchema,
  styleAnnotationSchema,
  renderableCommandSchema,
  targetVersionOf,
  replacePageSchema,
  sourceIdsOf,
  deskewPagesSchema,
  enhancePagesSchema,
  ocrPageSchema,
  resizePagesSchema,
  rotatePagesSchema,
  setLayerVisibilitySchema,
  setPageBackgroundSchema,
  setPageTransitionSchema,
  swapPagesSchema,
  watermarkPagesSchema,
} from './commands.js';
export {
  // The OCR language set, exported for the same reason the spelling one is: both
  // sides key a record on it — the provisioning table and the renderer's display
  // titles — so adding a language is two compile errors and a digest.
  AZURE_ENDPOINT_SETTING_ID,
  AZURE_KEY_SETTING_ID,
  DOCUMENT_ACCESS_VALUES,
  DOCUMENT_PASSWORD_MAX_CHARS,
  type DocumentAccess,
  OCR_ENGINES,
  OCR_LANGUAGES,
  TROCR_SIZES,
  type OcrEngine,
  type OcrLanguage,
  type TrocrSize,
  docIdSchema,
  docVersionSchema,
  envelopeSchema,
  fileHandleSchema,
  structuredErrorSchema,
} from './schemas.js';
