export {
  ANSWER_TOO_LARGE,
  answerCrossesInFile,
  type AnswerRoute,
  type Channel,
  type DeclaredOf,
  type FailureOf,
  INTERNAL_FAILURE,
  type InternalFailure,
  type ChannelMap,
  type ClientApi,
  type Handlers,
  type ParamsOf,
  type ResultOf,
  channel,
  fileAnswered,
  fileRequested,
  fileRequestedAndAnswered,
} from './channel.js';
export {
  type RouteViolation,
  WORST_BYTES_PER_CHAR,
  hostRouteViolations,
  maxEncodedBytes,
  unboundedMembers,
} from './schemaBound.js';
export {
  type ChannelId,
  type ChannelParams,
  type ChannelResult,
  type Channels,
  type ContractClient,
  type ContractHandlers,
  // Invariant L11's mechanism. Exported so a caller can size its reads under
  // the bound rather than discover it as a refusal.
  MAX_RANGE_BYTES,
  // The recent list's cap, RESTATED in `apps/desktop` because this package may
  // not import that one. Exported so the case that holds the two together has
  // something to compare against — without it the agreement is a sentence in
  // this file's comment and nothing else, which is what the audit of
  // `87540a5..HEAD` found it to be.
  MAX_RECENT_ENTRIES,
  RECENT_AVAILABILITY,
  type RecentAvailability,
  RECENT_CHECK_CAP_MS,
  // PART F's BACKUP COPIES, one table for the setting and `main`'s save.
  BACKUP_COPIES,
  type BackupCopies,
  BACKUP_COPIES_SETTING_ID,
  MAX_BACKUP_COPIES,
  MAX_SIGNATURES,
  // The text layer's two bounds. Exported because the caller that sizes a read
  // under the line limit is the renderer, and the per-line cap is what the
  // main-side reader passes to `textLayerOf` — a second spelling of either
  // would be the number this channel refuses on, written twice.
  MAX_RASTER_BYTES,
  MAX_RASTER_PIXELS,
  MAX_STRUCTURE_NAME,
  MAX_STRUCTURE_NODES,
  MAX_PDFA_REMOVAL_CHARS,
  MAX_PDFA_REMOVALS,
  MAX_TABLE_CELL_TEXT,
  MAX_TABLE_CELLS,
  TABLE_ENGINES,
  // Main's window names its methods by these; the renderer's edit commands name the verb they ask for.
  WINDOW_EDIT_ACTIONS,
  type WindowEditAction,
  // The Store application's pages: `main`'s URI table is keyed by them.
  STORE_PAGES,
  type StorePage,
  SERVICE_REFUSALS,
  SERVICE_PROBLEMS,
  SERVICE_PROBLEM_OF,
  MAX_SERVICE_DETAIL,
  MAX_TEXT_LAYER_LINE,
  MAX_TEXT_LAYER_LINES,
  MAX_PAGE_WORD_BOXES,
  // THE SEARCH QUERY'S BOUND, exported because the selected-text menu seeds the find field with a
  // selection, and cutting it to the channel's own bound keeps a long selection from being refused.
  MAX_QUERY_LENGTH,
  // NAMED BECAUSE THE KERNEL SEAM NOW READS IT TOO. ADR-0040's extension hands
  // a command's apply the outline as pre-read data, so this shape has a reader
  // that is not a channel; a second declaration there would be two of one thing.
  type OutlineEntry,
  outlineEntrySchema,
  // The dictionary set and its two bounds. The list is exported because BOTH
  // sides key a record on it — main's package map and the renderer's display
  // titles — which is what makes adding a language two compile errors rather
  // than a checklist.
  MAX_AFFIX_BYTES,
  MAX_DICTIONARY_BYTES,
  SPELLING_LANGUAGES,
  type SpellingLanguage,
  spellingLanguageSchema,
  channelIds,
  channels,
  NATIVE_COMPONENT_IDS,
  type NativeComponentId,
  // THE CAMERA'S FRAMES, exported because the capture dialog's result takes the same
  // schema the channel does, so the two cannot disagree about what may be sent.
  capturedFramesSchema,
  // THE BARCODE SET AND BOUNDS, exported because the placement dialog's result takes the same
  // enum and bound the channel does, and `contractHandlers.test.ts` holds them to the kernel's.
  BARCODE_FORMATS,
  ACCESSIBILITY_HUMAN_CHECKS,
  MAX_BARCODE_TEXT,
  MAX_PAGE_BARCODES,
  // A saved conversation's bounds and shape (ADR-0093): the renderer trims to them before a save,
  // and `main` validates a decrypted conversation against the same schema.
  MAX_CHAT_TEXT,
  MAX_CHAT_TURNS,
  MAX_MODEL_ID,
  // ONE LIST SHAPE for `ai.models` and the Settings dialog's props (ADR-0117).
  AI_LIST_PROBLEMS,
  type AiModelListAnswer,
  aiModelListSchema,
  type SavedTurn,
  savedTurnSchema,
  savedTurnsSchema,
  // WHAT AN EDITOR OVER A BLOCK IS SET IN (ADR-0096): the renderer reads it, and
  // main's composition answers it, from one schema.
  type TextBlockStyle,
  textBlockStyleSchema,
  // THE PRELOAD'S CHANNEL (ADR-0099): main registers it, and the page validates its answer with it.
  type DroppedOpenOutcome,
  // A RECENT FILE'S PLACE (ADR-0100): main builds it, the page shows it, and no channel takes one.
  type DisplayLocation,
  displayLocationSchema,
  KNOWN_FOLDERS,
  type KnownFolder,
  // NTFS's component bound, which main's location derivation drops a longer folder name at.
  MAX_DOCUMENT_NAME_LENGTH,
  // A recent card's picture: main's store refuses to keep one past the bound, and both sides read the setting.
  MAX_RECENT_PREVIEW_BYTES,
  RECENT_PREVIEWS_SETTING_ID,
  // THE SESSION'S BOUND, apart from the recent cap: what was open is not trimmed to what is remembered.
  MAX_SESSION_ENTRIES,
  CRASH_REPORTS_SETTING_ID,
  LOG_DETAIL_SETTING_ID,
  MAX_SETTINGS_FILE_BYTES,
  LOG_DETAILS,
  crashReportIdSchema,
  // THE UPDATE CHECK (ADR-0110): main parses the manifest and answers the status; the page reads the status, and
  // registers the check's switch only while the address is live.
  compareReleaseVersions,
  releaseVersionSchema,
  UPDATE_CHECK_SETTING_ID,
  UPDATE_MANIFEST,
  type UpdateManifest,
  type UpdateManifestAddress,
  updateManifestSchema,
  type UpdateStatus,
  updateStatusSchema,
  // The rating prompt's opt-out (E3): main reads it, the page declares its control.
  REVIEW_PROMPTS_SETTING_ID,
  // The first-run AI setup's switch: the page declares it, and every harness starts past it.
  AI_SETUP_AT_START_SETTING_ID,
  type MainHandlers,
  MAX_DROPPED_PATH_LENGTH,
  // How many documents one launch may name on its command line; main's reader takes no more.
  MAX_LAUNCH_DOCUMENTS,
  // How many blocks of a workbook an Office import may name as not converted.
  MAX_OFFICE_MISSING_BLOCKS,
  type PreloadChannels,
  type PreloadHandlers,
  preloadChannels,
  // THE PART SIZES of the lists that cross in parts (ADR-0130): main cuts a part at them.
  ANNOTATIONS_PART,
  DESTINATIONS_PART,
  FORM_FIELDS_PART,
  LAYERS_PART,
  PAGE_LINKS_PART,
  PAGE_OBJECTS_PART,
  TEXT_BLOCKS_PART,
} from './channels.js';
export { acceptAnswer, createClient, wrapHandler, wrapHandlers } from './boundary.js';
export { BRIDGE_KEY, type MonsteraBridge, PRELOAD_CHANNEL_IDS, type PreloadChannelId } from './bridge.js';
export {
  AI_ANSWER_REFUSALS,
  EVENTS,
  EVENT_IDS,
  MAX_EVENT_TEXT,
  type EventHandler,
  type EventId,
  type EventMap,
  type EventPayload,
  MAX_WEB_SOURCES,
  answerIdSchema,
  checkEvent,
  subscribeToEvent,
  subscriptionIdSchema,
  webSourceSchema,
} from './events.js';
export {
  type AnswerPiece,
  type AskAbout,
  type AskAboutOne,
  type AskAmong,
  type AskFile,
  type AskFileLabel,
  type AskFileUnread,
  type AskLabel,
  type AskSent,
  type AskSide,
  type AskSides,
  ASK_FILE_UNREAD,
  ASK_UNREAD_REASONS,
  MAX_ASK_ATTACHMENTS,
  MAX_ASK_CONTEXT,
  MAX_ASK_DOCUMENTS,
  MAX_ASK_SELECTION,
  askAboutSchema,
  askAmongSchema,
  askCitation,
  askFileSchema,
  askLabelWord,
  askPageMarker,
  askShareOf,
  askSentSchema,
  citationsIn,
  namesEachOnce,
  pairsWith,
} from './askAbout.js';
export {
  ENGINE_ANSWER_FILE_MAX_BYTES,
  ENGINE_HOST_FRAME_MAX_BYTES,
  ENGINE_HOST_MAX_IN_FLIGHT,
  HOST_CORRELATION_ID_MAX_CHARS,
  HOST_OUTPUT_NAME_MAX_CHARS,
  type HostRequest,
  type HostResponse,
  LARGEST_INTENT_PAYLOAD_BYTES,
  hostRequestSchema,
  hostResponseSchema,
  outputNameSchema,
} from './hostProtocol.js';
export {
  FRAME_HEADER_BYTES,
  FRAME_LENGTH_CEILING,
  FrameDecoder,
  type FrameViolation,
  encodeFrame,
} from './frame.js';
export { type Incident, IncidentLog, type IncidentSink } from './incident.js';
export {
  type AnnotationColour,
  type AnnotationDraft,
  type AnnotationKindName,
  type AnnotationPoint,
  type AnnotationRect,
  type BorderEffect,
  type LineEnding,
  annotationKindNameSchema,
  annotationPointSchema,
  borderEffectSchema,
  lineEndingSchema,
  MAX_POLYGON_POINTS,
  type Command,
  type CommandKind,
  type CommandOfKind,
  MAX_ANNOTATION_BORDER,
  MAX_ANNOTATION_FONT,
  ANNOTATION_FONTS,
  type AnnotationFont,
  annotationFontSchema,
  TEXT_DIRECTIONS,
  type TextDirection,
  textDirectionSchema,
  BUILT_IN_STAMPS,
  type BuiltInStamp,
  builtInStampSchema,
  LIBRARY_KINDS,
  type LibraryEntry,
  type LibraryId,
  type LibraryKind,
  MAX_LIBRARY_ENTRIES,
  MAX_LIBRARY_NAME,
  MAX_LIBRARY_PICTURE_BYTES,
  keepableSignatureSchema,
  libraryEntrySchema,
  libraryIdSchema,
  libraryKindSchema,
  LINK_SCHEMES,
  MAX_ANNOTATION_TEXT,
  MAX_REMOVED_ANNOTATIONS,
  MAX_LINK_URI,
  type AnnotationOpacity,
  annotationOpacitySchema,
  MIN_ANNOTATION_OPACITY,
  type LinkTarget,
  type MeasureScale,
  type MeasureUnit,
  measurePerPointSchema,
  measureScaleSchema,
  measureUnitSchema,
  MIN_ANNOTATION_FONT,
  MAX_INK_POINTS,
  MAX_PAGE_COORDINATE,
  MAX_MARKDOWN_BYTES,
  MAX_CSV_BYTES,
  MAX_OFFICE_IMPORT_BYTES,
  MAX_WORKBOOK_PARTS,
  MAX_WORKBOOK_ROW,
  MAX_WORKBOOK_SHEET_NAME,
  MAX_IMPORT_IMAGES,
  MAX_IMPORT_IMAGE_PIXELS,
  MAX_IMPORT_PNG_PIXELS,
  MAX_IMPORT_IMAGE_BYTES,
  addAnnotationSchema,
  addLinkSchema,
  annotationColourSchema,
  annotationDraftSchema,
  annotationRectSchema,
  batesNumberPagesSchema,
  commandSchema,
  // EVERY MEMBER, not just the first. `rotatePagesSchema` was exported alone
  // because one caller wanted one schema; the engine host's channels need the
  // MuPDF-routed subset as a union of its own, and a subset cannot be built
  // from a union whose members are unreachable
  // ([ADR-0039](../../../docs/DECISIONS/0039-a-byte-image-writer-round-trips-the-live-session.md)).
  cropPagesSchema,
  deletePagesSchema,
  duplicatePageSchema,
  generateTocSchema,
  headerFooterPagesSchema,
  STAMP_TOKENS,
  insertBlankPageSchema,
  MAX_IMAGE_BYTES,
  type RenderableCommand,
  insertImagePageSchema,
  mergeDocumentSchema,
  movePageSchema,
  type NamesAnAnnotation,
  type NamesAFormField,
  type NamesATextObject,
  type NamesAPage,
  type NamesASecondDocument,
  MAX_EDIT_RUNS,
  MAX_EDIT_TEXT,
  MAX_OBJECT_INDEX,
  type BlockEdit,
  type EditedBlock,
  type TextReplacement,
  blockEditAgrees,
  blockEditOf,
  blockEditSchema,
  blocksOfEdit,
  replacementFieldsOf,
  replacementsOf,
  editTextBlockSchema,
  MAX_EDITED_OBJECTS,
  MAX_FIND_TEXT,
  MAX_OBJECT_SCALE,
  MIN_OBJECT_SCALE,
  replaceAllTextSchema,
  replaceTextObjectSchema,
  placePageObjectSchema,
  recolorPageObjectsSchema,
  deletePageObjectsSchema,
  promoteFormObjectsSchema,
  type FieldFill,
  type FormFieldKind,
  type CreatedField,
  createFormFieldSchema,
  createdFieldPlacementSchema,
  createdFieldSchema,
  simpleCreatedFieldSchema,
  MAX_CREATED_FIELDS,
  deleteFormFieldsSchema,
  fieldFillSchema,
  fillFormFieldSchema,
  flattenFormFieldsSchema,
  PDF_ENCRYPTIONS,
  PDF_PERMISSIONS,
  type PdfEncryption,
  type PdfPermission,
  setDocumentProtectionSchema,
  applyRedactionsSchema,
  markMatchesForRedactionSchema,
  sanitizeDocumentSchema,
  signDocumentSchema,
  MAX_SIGNATURE_FIELD,
  MAX_SIGNATURE_STROKE_POINTS,
  MAX_SIGNATURE_STROKES,
  MAX_PLACED_SIGNATURE_POINTS,
  type KeepableSignature,
  type DrawableSignature,
  drawableSignatureSchema,
  keptLookOf,
  type KeptSignatureFont,
  MAX_SIGNATURE_OUTLINE_POINTS,
  outlinedSignatureMarkSchema,
  type OutlinedSignatureMark,
  outlinePointsOf,
  outlineOpCodes,
  outlineOpsArePath,
  OUTLINE_OPS,
  type OutlineOp,
  type PlacedDrawing,
  type PlacedSignatureMark,
  placedMarkOf,
  strokesOfPlaced,
  requestedSignatureMarkSchema,
  type RequestedSignatureMark,
  chosenSignatureMarkSchema,
  type ChosenSignatureMark,
  RETIRED_SIGNATURE_FONTS,
  SIGNATURE_FONTS,
  SIGNATURE_OUTLINE_GRID,
  type SignatureFont,
  type SignatureOutline,
  signatureFontOf,
  type TypedSignatureMark,
  typedSignatureMarkSchema,
  drawnSignatureMarkSchema,
  SIGN_REFUSALS,
  type SignRefusal,
  TIMESTAMP_AUTHORITIES,
  TIMESTAMP_AUTHORITY_IDS,
  type TimestampAuthority,
  signaturePlacementSchema,
  type SignaturePlacement,
  PDF_SANITIZE_PARTS,
  type PdfSanitizePart,
  MAX_REDACT_MATCHES_PER_PAGE,
  PDF_REDACT_COVERS,
  PDF_REDACT_IMAGES,
  type PdfRedactCover,
  type PdfRedactImages,
  type FormDataFormat,
  type FormDataImportFormat,
  formDataFormatSchema,
  formDataImportFormatSchema,
  formFieldKindSchema,
  importFormDataSchema,
  type AnnotationDataFormat,
  annotationDataFormatSchema,
  importAnnotationsSchema,
  annotationBlendSchema,
  type AnnotationBlend,
  annotationAuthorSchema,
  annotationInstantSchema,
  annotationStampSchema,
  type AnnotationStamp,
  type DispatchableCommand,
  withStamp,
  MAX_ANNOTATION_AUTHOR,
  KEEPS_THE_ANNOTATION_WALK,
  keepsTheAnnotationWalk,
  type WalkKeepingKind,
  MAX_ANNOTATION_DATA_BYTES,
  MAX_DELETED_FIELDS,
  MAX_FORM_DATA_BYTES,
  MAX_FIELD_NAME,
  MAX_FIELD_OPTION,
  MAX_FIELD_OPTIONS,
  MAX_FIELD_VALUE,
  placeAnnotationSchema,
  placeImageSchema,
  placeSignatureMarkSchema,
  placeSignaturePictureSchema,
  removeAnnotationSchema,
  styleAnnotationSchema,
  setAnnotationAuthorSchema,
  renderableCommandSchema,
  targetVersionOf,
  withTargetVersion,
  replacePageSchema,
  importPageAsLayerSchema,
  sourceIdsOf,
  deskewPagesSchema,
  enhancePagesSchema,
  straightenScansSchema,
  ocrPageSchema,
  resizePagesSchema,
  rotatePagesSchema,
  setLayerVisibilitySchema,
  setPageBackgroundSchema,
  setPageTransitionSchema,
  swapPagesSchema,
  watermarkPagesSchema,
} from './commands.js';
export {
  // A command's pages as runs (decision D, finding AAA-1): the renderer writes them, the kernel expands them.
  MAX_PAGE_INDEX,
  MAX_PAGE_SET_ENTRIES,
  type PageSet,
  pageSetOf,
  pageSetSchema,
  pagesOfSet,
  withPageRuns,
} from './pageSet.js';
export {
  // The Word export's modes: the renderer, main and the MuPDF host take the one list (ADR-0072).
  WORD_MODES,
  type WordMode,
} from './wordModes.js';
export {
  // The OCR language set, exported for the same reason the spelling one is: both
  // sides key a record on it — the provisioning table and the renderer's display
  // titles — so adding a language is two compile errors and a digest.
  AZURE_ENDPOINT_SETTING_ID,
  AZURE_KEY_SETTING_ID,
  SECRET_SETTING_IDS,
  type SecretSettingId,
  ANTHROPIC_KEY_SETTING_ID,
  DOCUSIGN_ENVIRONMENT_SETTING_ID,
  DOCUSIGN_ENVIRONMENTS,
  DOCUSIGN_INTEGRATION_KEY_SETTING_ID,
  type DocusignEnvironment,
  DOCUSIGN_REFUSALS,
  type DocusignRefusalKind,
  COMPOSE_REFUSALS,
  type ComposeRefusal,
  OPTIMIZE_SETTINGS,
  OPTIMIZE_SETTING_NAMES,
  type OptimizeSetting,
  URL_FETCH_REFUSALS,
  type UrlFetchRefusal,
  FILE_ACCESS,
  type FileAccess,
  SAVE_WRITE_CAUSES,
  type SaveWriteCause,
  MAX_DOCUSIGN_RECIPIENT_FIELD,
  MAX_DOCUSIGN_SIGNERS,
  MAX_DOCUSIGN_SUBJECT,
  NETWORK_OCR_ENGINES,
  type NetworkOcrEngine,
  isNetworkOcrEngine,
  MAX_SNAPSHOT_SCALE,
  MIN_SNAPSHOT_SCALE,
  MIN_PAGE_PICTURE_SCALE,
  PAGE_IMAGE_FORMATS,
  type PageImageFormat,
  MIN_PAGE_IMAGE_DPI,
  MAX_PAGE_IMAGE_DPI,
  MIN_IMAGE_QUALITY,
  MAX_IMAGE_QUALITY,
  DOCUMENT_ACCESS_VALUES,
  DOCUMENT_PASSWORD_MAX_CHARS,
  type DocumentAccess,
  OCR_ENGINES,
  OCR_LANGUAGES,
  ocrEngineSchema,
  ocrLanguageSchema,
  ocrLanguagesSchema,
  MAX_OCR_LANGUAGES,
  type OcrEngine,
  type OcrLanguage,
  type OcrLanguages,
  DOC_ID_MAX_CHARS,
  docIdSchema,
  docVersionSchema,
  envelopeSchema,
  fileHandleSchema,
  structuredErrorSchema,
} from './schemas.js';
export {
  TRANSLATION_LANGUAGES,
  TRANSLATION_LANGUAGE_IDS,
  type TranslationLanguage,
} from './translationLanguages.js';
export {
  AI_MODELS_SETTING_ID,
  AI_PROVIDERS,
  AI_PROVIDER_IDS,
  AI_PROVIDER_KEY_SETTING_IDS,
  AI_PROVIDER_SETTING_ID,
  AZURE_OPENAI_ENDPOINT_SETTING_ID,
  CHAT_HISTORY_SETTING_ID,
  WEB_SEARCH_ABSENCES,
  choiceReadsImages,
  defaultModel,
  servesVision,
  webSearchOf,
  type AiModel,
  type AiModelCapabilities,
  type AiProvider,
  type AiProviderId,
  type WebSearchAbsence,
  type WebSearchSupport,
} from './aiProviders.js';
export {
  CLOUD_PICKER_PROVIDER_IDS,
  CLOUD_PROVIDER_IDS,
  CLOUD_REFUSALS,
  type CloudFile,
  type CloudPickerProviderId,
  type CloudProviderId,
  type CloudRefusal,
  type CloudState,
  MAX_CLOUD_FILES,
  MAX_CLOUD_FILE_ID,
  MAX_CLOUD_FILE_NAME,
  cloudFileSchema,
  cloudPickerProviderSchema,
  cloudProviderSchema,
  cloudStateSchema,
} from './cloudProviders.js';
export {
  AI_MODELS_STORED,
  AZURE_ENDPOINT_STORED,
  AZURE_OPENAI_ENDPOINT_STORED,
  BACKUP_COPIES_STORED,
  CHAT_HISTORY_STORED,
  CRASH_REPORTS_STORED,
  DOCUSIGN_ENVIRONMENT_STORED,
  LOG_DETAIL_STORED,
  RECENT_PREVIEWS_STORED,
  REVIEW_PROMPTS_STORED,
  STORED_SETTINGS,
  UPDATE_CHECK_STORED,
  storedSetting,
  type StoredSetting,
  type TextSetting,
} from './storedSettings.js';
