export {
  type Channel,
  type DeclaredOf,
  type FailureOf,
  INTERNAL_FAILURE,
  type InternalFailure,
  type ChannelMap,
  type ClientApi,
  type Handlers,
  type ParamsOf,
  type ResultOf,
  channel,
} from './channel.js';
export {
  type ChannelId,
  type ChannelParams,
  type ChannelResult,
  type Channels,
  type ContractClient,
  type ContractHandlers,
  // Invariant L11's mechanism. Exported so a caller can size its reads under
  // the bound rather than discover it as a refusal.
  MAX_RANGE_BYTES,
  // The recent list's cap, RESTATED in `apps/desktop` because this package may
  // not import that one. Exported so the case that holds the two together has
  // something to compare against — without it the agreement is a sentence in
  // this file's comment and nothing else, which is what the audit of
  // `87540a5..HEAD` found it to be.
  MAX_RECENT_ENTRIES,
  MAX_SIGNATURES,
  // The text layer's two bounds. Exported because the caller that sizes a read
  // under the line limit is the renderer, and the per-line cap is what the
  // main-side reader passes to `textLayerOf` — a second spelling of either
  // would be the number this channel refuses on, written twice.
  MAX_RASTER_BYTES,
  MAX_RASTER_PIXELS,
  MAX_STRUCTURE_NAME,
  MAX_STRUCTURE_NODES,
  MAX_PDFA_REMOVAL_CHARS,
  MAX_PDFA_REMOVALS,
  MAX_TABLE_CELL_TEXT,
  MAX_TABLE_CELLS,
  TABLE_ENGINES,
  SERVICE_REFUSALS,
  SERVICE_PROBLEMS,
  SERVICE_PROBLEM_OF,
  MAX_SERVICE_DETAIL,
  MAX_TEXT_LAYER_LINE,
  MAX_TEXT_LAYER_LINES,
  // THE SEARCH QUERY'S BOUND, exported because the selected-text menu seeds the find field with a
  // selection, and cutting it to the channel's own bound keeps a long selection from being refused.
  MAX_QUERY_LENGTH,
  // NAMED BECAUSE THE KERNEL SEAM NOW READS IT TOO. ADR-0040's extension hands
  // a command's apply the outline as pre-read data, so this shape has a reader
  // that is not a channel; a second declaration there would be two of one thing.
  type OutlineEntry,
  outlineEntrySchema,
  // The dictionary set and its two bounds. The list is exported because BOTH
  // sides key a record on it — main's package map and the renderer's display
  // titles — which is what makes adding a language two compile errors rather
  // than a checklist.
  MAX_AFFIX_BYTES,
  MAX_DICTIONARY_BYTES,
  SPELLING_LANGUAGES,
  type SpellingLanguage,
  spellingLanguageSchema,
  channelIds,
  channels,
  // THE CAMERA'S FRAMES, exported because the capture dialog's result takes the same
  // schema the channel does, so the two cannot disagree about what may be sent.
  capturedFramesSchema,
  // THE BARCODE SET AND BOUNDS, exported because the placement dialog's result takes the same
  // enum and bound the channel does, and `contractHandlers.test.ts` holds them to the kernel's.
  BARCODE_FORMATS,
  ACCESSIBILITY_HUMAN_CHECKS,
  MAX_BARCODE_TEXT,
  MAX_PAGE_BARCODES,
  // A saved conversation's bounds and shape (ADR-0093): the renderer trims to them before a save,
  // and `main` validates a decrypted conversation against the same schema.
  MAX_CHAT_TEXT,
  MAX_CHAT_TURNS,
  MAX_MODEL_ID,
  type SavedTurn,
  savedTurnSchema,
  savedTurnsSchema,
  // WHAT AN EDITOR OVER A BLOCK IS SET IN (ADR-0096): the renderer reads it, and
  // main's composition answers it, from one schema.
  type TextBlockStyle,
  textBlockStyleSchema,
  // THE PRELOAD'S CHANNEL (ADR-0099): main registers it, and the page validates its answer with it.
  type DroppedOpenOutcome,
  // A RECENT FILE'S PLACE (ADR-0100): main builds it, the page shows it, and no channel takes one.
  type DisplayLocation,
  displayLocationSchema,
  KNOWN_FOLDERS,
  type KnownFolder,
  // NTFS's component bound, which main's location derivation drops a longer folder name at.
  MAX_DOCUMENT_NAME_LENGTH,
  type MainHandlers,
  MAX_DROPPED_PATH_LENGTH,
  type PreloadChannels,
  type PreloadHandlers,
  preloadChannels,
} from './channels.js';
export { acceptAnswer, createClient, wrapHandler, wrapHandlers } from './boundary.js';
export { BRIDGE_KEY, type MonsteraBridge, PRELOAD_CHANNEL_IDS, type PreloadChannelId } from './bridge.js';
export {
  AI_ANSWER_REFUSALS,
  EVENTS,
  EVENT_IDS,
  MAX_EVENT_TEXT,
  type EventHandler,
  type EventId,
  type EventMap,
  type EventPayload,
  checkEvent,
  subscribeToEvent,
  subscriptionIdSchema,
} from './events.js';
export {
  type AnswerPiece,
  type AskAbout,
  type AskSent,
  type AskSide,
  type AskSides,
  MAX_ASK_CONTEXT,
  MAX_ASK_SELECTION,
  askAboutSchema,
  askCitation,
  askPageMarker,
  askSentSchema,
  citationsIn,
  pairsWith,
} from './askAbout.js';
export {
  ENGINE_HOST_FRAME_MAX_BYTES,
  ENGINE_HOST_MAX_IN_FLIGHT,
  HOST_CORRELATION_ID_MAX_CHARS,
  type HostRequest,
  type HostResponse,
  LARGEST_INTENT_PAYLOAD_BYTES,
  hostRequestSchema,
  hostResponseSchema,
} from './hostProtocol.js';
export {
  FRAME_HEADER_BYTES,
  FRAME_LENGTH_CEILING,
  FrameDecoder,
  type FrameViolation,
  encodeFrame,
} from './frame.js';
export { type Incident, IncidentLog, type IncidentSink } from './incident.js';
export {
  type AnnotationColour,
  type AnnotationDraft,
  type AnnotationKindName,
  type AnnotationPoint,
  type AnnotationRect,
  type BorderEffect,
  type LineEnding,
  annotationKindNameSchema,
  annotationPointSchema,
  borderEffectSchema,
  lineEndingSchema,
  MAX_POLYGON_POINTS,
  type Command,
  type CommandKind,
  type CommandOfKind,
  MAX_ANNOTATION_BORDER,
  MAX_ANNOTATION_FONT,
  LINK_SCHEMES,
  MAX_ANNOTATION_TEXT,
  MAX_REMOVED_ANNOTATIONS,
  MAX_LINK_URI,
  type AnnotationOpacity,
  annotationOpacitySchema,
  MIN_ANNOTATION_OPACITY,
  type LinkTarget,
  type MeasureScale,
  type MeasureUnit,
  measurePerPointSchema,
  measureScaleSchema,
  measureUnitSchema,
  MIN_ANNOTATION_FONT,
  MAX_INK_POINTS,
  MAX_PAGE_COORDINATE,
  MAX_MARKDOWN_BYTES,
  MAX_CSV_BYTES,
  MAX_IMPORT_IMAGES,
  MAX_IMPORT_IMAGE_PIXELS,
  MAX_IMPORT_PNG_PIXELS,
  MAX_IMPORT_IMAGE_BYTES,
  addAnnotationSchema,
  addLinkSchema,
  annotationColourSchema,
  annotationDraftSchema,
  annotationRectSchema,
  batesNumberPagesSchema,
  commandSchema,
  // EVERY MEMBER, not just the first. `rotatePagesSchema` was exported alone
  // because one caller wanted one schema; the engine host's channels need the
  // MuPDF-routed subset as a union of its own, and a subset cannot be built
  // from a union whose members are unreachable
  // ([ADR-0039](../../../docs/DECISIONS/0039-a-byte-image-writer-round-trips-the-live-session.md)).
  cropPagesSchema,
  deletePagesSchema,
  duplicatePageSchema,
  generateTocSchema,
  headerFooterPagesSchema,
  insertBlankPageSchema,
  MAX_IMAGE_BYTES,
  type RenderableCommand,
  insertImagePageSchema,
  mergeDocumentSchema,
  movePageSchema,
  type NamesAnAnnotation,
  type NamesAFormField,
  type NamesATextObject,
  type NamesAPage,
  type NamesASecondDocument,
  MAX_REPLACED_TEXT,
  MAX_TEXT_REPLACEMENTS,
  MAX_BLOCK_LINES,
  MAX_EDIT_BLOCKS,
  editTextBlockSchema,
  MAX_EDITED_OBJECTS,
  MAX_FIND_TEXT,
  MAX_OBJECT_SCALE,
  MIN_OBJECT_SCALE,
  replaceAllTextSchema,
  replaceTextObjectSchema,
  placePageObjectSchema,
  recolorPageObjectsSchema,
  deletePageObjectsSchema,
  promoteFormObjectsSchema,
  type FieldFill,
  type FormFieldKind,
  type CreatedField,
  createFormFieldSchema,
  createdFieldSchema,
  deleteFormFieldsSchema,
  fieldFillSchema,
  fillFormFieldSchema,
  flattenFormFieldsSchema,
  PDF_ENCRYPTIONS,
  PDF_PERMISSIONS,
  type PdfEncryption,
  type PdfPermission,
  setDocumentProtectionSchema,
  applyRedactionsSchema,
  markMatchesForRedactionSchema,
  sanitizeDocumentSchema,
  signDocumentSchema,
  MAX_SIGNATURE_FIELD,
  MAX_SIGNATURE_STROKE_POINTS,
  MAX_SIGNATURE_STROKES,
  requestedSignatureMarkSchema,
  type RequestedSignatureMark,
  SIGNATURE_FONTS,
  SIGN_REFUSALS,
  type SignRefusal,
  TIMESTAMP_AUTHORITIES,
  TIMESTAMP_AUTHORITY_IDS,
  type TimestampAuthority,
  signaturePlacementSchema,
  type SignaturePlacement,
  PDF_SANITIZE_PARTS,
  type PdfSanitizePart,
  MAX_REDACT_MATCHES_PER_PAGE,
  PDF_REDACT_COVERS,
  PDF_REDACT_IMAGES,
  type PdfRedactCover,
  type PdfRedactImages,
  type FormDataFormat,
  type FormDataImportFormat,
  formDataFormatSchema,
  formDataImportFormatSchema,
  formFieldKindSchema,
  importFormDataSchema,
  type AnnotationDataFormat,
  annotationDataFormatSchema,
  importAnnotationsSchema,
  annotationBlendSchema,
  type AnnotationBlend,
  annotationAuthorSchema,
  annotationInstantSchema,
  annotationStampSchema,
  type AnnotationStamp,
  type DispatchableCommand,
  withStamp,
  MAX_ANNOTATION_AUTHOR,
  KEEPS_THE_ANNOTATION_WALK,
  keepsTheAnnotationWalk,
  type WalkKeepingKind,
  MAX_ANNOTATION_DATA_BYTES,
  MAX_DELETED_FIELDS,
  MAX_FORM_DATA_BYTES,
  MAX_FIELD_NAME,
  MAX_FIELD_OPTION,
  MAX_FIELD_OPTIONS,
  MAX_FIELD_VALUE,
  placeAnnotationSchema,
  placeImageSchema,
  MAX_IMAGE_PAGES,
  removeAnnotationSchema,
  styleAnnotationSchema,
  setAnnotationAuthorSchema,
  renderableCommandSchema,
  targetVersionOf,
  replacePageSchema,
  importPageAsLayerSchema,
  sourceIdsOf,
  deskewPagesSchema,
  enhancePagesSchema,
  straightenScansSchema,
  ocrPageSchema,
  resizePagesSchema,
  rotatePagesSchema,
  setLayerVisibilitySchema,
  setPageBackgroundSchema,
  setPageTransitionSchema,
  swapPagesSchema,
  watermarkPagesSchema,
} from './commands.js';
export {
  // The OCR language set, exported for the same reason the spelling one is: both
  // sides key a record on it — the provisioning table and the renderer's display
  // titles — so adding a language is two compile errors and a digest.
  AZURE_ENDPOINT_SETTING_ID,
  AZURE_KEY_SETTING_ID,
  SECRET_SETTING_IDS,
  type SecretSettingId,
  ANTHROPIC_KEY_SETTING_ID,
  DOCUSIGN_ENVIRONMENT_SETTING_ID,
  DOCUSIGN_ENVIRONMENTS,
  DOCUSIGN_INTEGRATION_KEY_SETTING_ID,
  type DocusignEnvironment,
  DOCUSIGN_REFUSALS,
  type DocusignRefusalKind,
  COMPOSE_REFUSALS,
  type ComposeRefusal,
  OPTIMIZE_SETTINGS,
  OPTIMIZE_SETTING_NAMES,
  type OptimizeSetting,
  URL_FETCH_REFUSALS,
  type UrlFetchRefusal,
  MAX_DOCUSIGN_RECIPIENT_FIELD,
  MAX_DOCUSIGN_SIGNERS,
  MAX_DOCUSIGN_SUBJECT,
  NETWORK_OCR_ENGINES,
  type NetworkOcrEngine,
  isNetworkOcrEngine,
  MAX_SNAPSHOT_SCALE,
  MIN_SNAPSHOT_SCALE,
  PAGE_IMAGE_FORMATS,
  type PageImageFormat,
  MIN_PAGE_IMAGE_DPI,
  MAX_PAGE_IMAGE_DPI,
  MIN_IMAGE_QUALITY,
  MAX_IMAGE_QUALITY,
  DOCUMENT_ACCESS_VALUES,
  DOCUMENT_PASSWORD_MAX_CHARS,
  type DocumentAccess,
  OCR_ENGINES,
  OCR_LANGUAGES,
  ocrEngineSchema,
  ocrLanguageSchema,
  type OcrEngine,
  type OcrLanguage,
  docIdSchema,
  docVersionSchema,
  envelopeSchema,
  fileHandleSchema,
  structuredErrorSchema,
} from './schemas.js';
export {
  TRANSLATION_LANGUAGES,
  TRANSLATION_LANGUAGE_IDS,
  type TranslationLanguage,
} from './translationLanguages.js';
export {
  AI_PROVIDERS,
  AI_PROVIDER_IDS,
  AI_PROVIDER_KEY_SETTING_IDS,
  AZURE_OPENAI_ENDPOINT_SETTING_ID,
  CHAT_HISTORY_SETTING_ID,
  type AiModel,
  type AiModelCapabilities,
  type AiProvider,
  type AiProviderId,
} from './aiProviders.js';
export {
  CLOUD_PROVIDER_IDS,
  CLOUD_REFUSALS,
  type CloudFile,
  type CloudProviderId,
  type CloudRefusal,
  type CloudState,
  MAX_CLOUD_FILES,
  MAX_CLOUD_FILE_ID,
  MAX_CLOUD_FILE_NAME,
  cloudFileSchema,
  cloudProviderSchema,
  cloudStateSchema,
} from './cloudProviders.js';
