import * as mupdf from 'mupdf';
import type { PDFDocument, PDFObject } from 'mupdf';
import { z } from 'zod';

import type { AnnotationDataFormat } from '@monstera/contract';

import type { CaptureResult } from './commandLog.js';
import type { Apply, Invert, MupdfSession } from './engineSeam.js';
import { fdfFile, pdfName, pdfString, xmlCanCarry, xmlEscaped } from './interchangeEncoding.js';
import { withDocument } from './mupdfWriter.js';
import { annotationAt, markAuthored, pageAt, redraw } from './pageAnnotations.js';
import { type XfdfAnnotation, readXfdfAnnotations } from './xfdfReader.js';

/**
 * Annotations to and from a file — D8's *annotation import / export*, in JSON, XFDF and FDF
 * ([ADR-0077](../../../docs/DECISIONS/0077-annotations-are-exchanged-as-dictionary-entries-in-user-space.md)).
 *
 * ## The record is the annotation's own dictionary entries, in PDF user space
 *
 * Not an authoring draft: a draft is a drag — a highlight's two ends, from which MuPDF finds the
 * text — so a highlight read back into one has already lost its quadrilaterals. And not MuPDF's
 * getters and setters, which answer in the displayed page frame: measured 2026-09-17, a square
 * whose `/Rect` is `[100 100 300 200]` reads back from `getRect` as `[101 593 299 691]`. The entries
 * themselves are in user space, which is the space XFDF and FDF carry, so they are read and written
 * with no transform between — and measured the same day, entries written raw render on an upright
 * and a rotated page alike (1,783 pixels of ink each), and a save writes the appearance stream from
 * them (for a red square of width 7: `7 w`, `1 0 0 RG` and the box inset by half the width).
 *
 * ## A closed set of entries, never a copied dictionary
 *
 * A dictionary from a stranger's file can carry an action, a JavaScript entry or an appearance
 * stream whose content this build would then draw (invariant 24). So the record names the entries
 * that describe an annotation — its box, colours, opacity, border, text, author, subject, date and
 * geometry — and each is checked by one schema whichever format it came from. The appearance is
 * regenerated by MuPDF from those entries.
 */

/** The subtypes exchanged: every markup this build can list, and nothing that carries a file or a sound. */
export const INTERCHANGE_SUBTYPES = [
  'Text',
  'FreeText',
  'Line',
  'Square',
  'Circle',
  'Polygon',
  'PolyLine',
  'Highlight',
  'Underline',
  'Squiggly',
  'StrikeOut',
  'Caret',
  'Ink',
  'Redact',
] as const;

export type InterchangeSubtype = (typeof INTERCHANGE_SUBTYPES)[number];

/** How many annotations one file carries. The XFDF reader's bound and this one are the same number. */
export const MAX_INTERCHANGE_ANNOTATIONS = 4096;

/** How many points one geometry list holds. */
export const MAX_INTERCHANGE_POINTS = 4096;

/** How long an annotation's text may be; an author, subject or date is bounded at 512. */
const MAX_INTERCHANGE_TEXT = 16_384;
const MAX_INTERCHANGE_LABEL = 512;

/** The line endings the format defines. */
const LINE_ENDINGS = [
  'None',
  'Square',
  'Circle',
  'Diamond',
  'OpenArrow',
  'ClosedArrow',
  'Butt',
  'ROpenArrow',
  'RClosedArrow',
  'Slash',
] as const;

/** The icons a `/Text` note may name (PDF 32000-1, 12.5.6.4). */
const NOTE_ICONS = ['Comment', 'Key', 'Note', 'Help', 'NewParagraph', 'Paragraph', 'Insert'] as const;

/** A font resource name a default appearance may use. */
const FONT_NAME = /^\/[A-Za-z][A-Za-z0-9]{0,31}$/u;
/**
 * A font size: up to three digits and six places — `0` is the format's *auto*. SIX, as a colour
 * component has, because a PDF real has no fixed precision and producers write six: a free-text
 * box from another program carried `N.NNNNNN Tf`, and four places refused it (2026-09-21).
 */
const FONT_SIZE = /^\d{1,3}(\.\d{1,6})?$/u;
/** A colour component as the old pattern admitted one. */
const COMPONENT = /^-?\d{0,3}(\.\d{1,6})?$/u;
/**
 * The operators a default appearance may carry besides `Tf`, each with its operand count, in the
 * order the canonical form writes them. A fill colour (one of `g rg k`) and a stroke colour (one of
 * `G RG K`) are a slot each; the text-state operators are one number each. Measured 2026-09-21: a
 * free-text box from another program carried `TL` and `RG` as well, legal and harmless, and the
 * narrower reader silently dropped the whole appearance from its record.
 */
const APPEARANCE_OPERATORS: readonly { readonly slot: string; readonly operators: Readonly<Record<string, number>> }[] = [
  { slot: 'fill', operators: { g: 1, rg: 3, k: 4 } },
  { slot: 'stroke', operators: { G: 1, RG: 3, K: 4 } },
  { slot: 'TL', operators: { TL: 1 } },
  { slot: 'Tc', operators: { Tc: 1 } },
  { slot: 'Tw', operators: { Tw: 1 } },
  { slot: 'Tz', operators: { Tz: 1 } },
  { slot: 'Ts', operators: { Ts: 1 } },
];

/**
 * A default appearance, read as the format defines one, and written back in ONE order.
 *
 * PDF 32000-1 12.7.3.3 makes `/DA` a fragment of content stream that must hold a `Tf`; it fixes
 * no order. This used to be a pattern of MuPDF's own output — font, size, `Tf`, then a colour —
 * which is a second opinion about the format (B3a), and it refused the first file another program
 * wrote: PDF-XChange Editor 10.7.5 puts the colour first, `0 0 0 rg /F1 12 Tf`, and the whole
 * import was refused over one typewriter box (measured 2026-09-21).
 *
 * So the string is read as operands and operators: exactly one `Tf` with a font name and a size,
 * and at most one of each slot in {@link APPEARANCE_OPERATORS}, each with its own count of
 * numbers, in any order and any whitespace. Any other operator, a second `Tf` or a second of any
 * slot, or an operand left over is refused — `q`, `cm`, `BT` and the rest are content-stream
 * syntax from a stranger's file. The answer is the canonical form, `Tf` first and the slots in
 * their listed order — `/F1 12 Tf 0 0 0 rg` — so a record's appearance has one spelling however
 * it arrived.
 *
 * @returns the canonical string, or `null` when the text is not a default appearance this accepts.
 */
export function canonicalDefaultAppearance(text: string): string | null {
  const tokens = text.split(/[\0\t\n\f\r ]+/u).filter((token) => token !== '');
  let font: string | null = null;
  const slots = new Map<string, string>();
  let operands: string[] = [];
  for (const token of tokens) {
    const entry = APPEARANCE_OPERATORS.find((each) => each.operators[token] !== undefined);
    if (token === 'Tf') {
      const [name, size] = operands;
      if (font !== null || operands.length !== 2 || name === undefined || size === undefined) return null;
      if (!FONT_NAME.test(name) || !FONT_SIZE.test(size)) return null;
      font = `${name} ${size} Tf`;
    } else if (entry !== undefined) {
      if (slots.has(entry.slot) || operands.length !== entry.operators[token]) return null;
      if (!operands.every((operand) => operand !== '' && operand !== '-' && COMPONENT.test(operand))) return null;
      slots.set(entry.slot, `${operands.join(' ')} ${token}`);
    } else if (FONT_NAME.test(token) || COMPONENT.test(token)) {
      operands.push(token);
      continue;
    } else {
      return null;
    }
    operands = [];
  }
  if (font === null || operands.length > 0) return null;
  const rest = APPEARANCE_OPERATORS.flatMap((each) => {
    const written = slots.get(each.slot);
    return written === undefined ? [] : [written];
  });
  return [font, ...rest].join(' ');
}

/** A PDF date as annotations carry one: `D:` and up to the format's fields. */
const PDF_DATE = /^D:\d{4}[0-9+\-Z']{0,19}$/u;

// FINITE BY zod 4's OWN RULE: `z.number()` refuses Infinity and NaN.
const coordinate = z.number().min(-1e7).max(1e7);
const colour = z
  .array(z.number().min(0).max(1))
  .refine((components) => [0, 1, 3, 4].includes(components.length), 'a colour has 0, 1, 3 or 4 components');
const points = z
  .array(coordinate)
  .max(MAX_INTERCHANGE_POINTS * 2)
  .refine((numbers) => numbers.length % 2 === 0, 'points come in pairs');

/** One exchanged annotation, checked the same way whichever format it came from. */
export const interchangeAnnotationSchema = z
  .object({
    /** Zero-based, as XFDF's own `page` attribute is. */
    page: z.number().int().nonnegative(),
    subtype: z.enum(INTERCHANGE_SUBTYPES),
    rect: z.tuple([coordinate, coordinate, coordinate, coordinate]),
    colour: colour.optional(),
    interiorColour: colour.optional(),
    opacity: z.number().min(0).max(1).optional(),
    borderWidth: z.number().min(0).max(1000).optional(),
    contents: z.string().max(MAX_INTERCHANGE_TEXT).optional(),
    author: z.string().max(MAX_INTERCHANGE_LABEL).optional(),
    subject: z.string().max(MAX_INTERCHANGE_LABEL).optional(),
    modified: z.string().max(64).regex(PDF_DATE).optional(),
    quadPoints: points.refine((numbers) => numbers.length % 8 === 0, 'quadrilaterals have eight numbers').optional(),
    inkList: z.array(points).min(1).max(256).optional(),
    vertices: points.optional(),
    line: z.tuple([coordinate, coordinate, coordinate, coordinate]).optional(),
    lineEndings: z.tuple([z.enum(LINE_ENDINGS), z.enum(LINE_ENDINGS)]).optional(),
    icon: z.enum(NOTE_ICONS).optional(),
    defaultAppearance: z
      .string()
      .max(128)
      .transform((text, context) => {
        const canonical = canonicalDefaultAppearance(text);
        if (canonical === null) {
          context.addIssue({ code: 'custom', message: 'a default appearance is one Tf and at most one colour operator' });
          return z.NEVER;
        }
        return canonical;
      })
      .optional(),
  })
  .strict()
  .superRefine((record, context) => {
    // THE GEOMETRY A SUBTYPE IS DRAWN FROM is required, because without it MuPDF draws nothing
    // and the import would report an annotation a person cannot see.
    const needs: Partial<Record<InterchangeSubtype, keyof typeof record>> = {
      Highlight: 'quadPoints',
      Underline: 'quadPoints',
      Squiggly: 'quadPoints',
      StrikeOut: 'quadPoints',
      Ink: 'inkList',
      Polygon: 'vertices',
      PolyLine: 'vertices',
      Line: 'line',
    };
    const needed = needs[record.subtype];
    if (needed !== undefined && record[needed] === undefined) {
      context.addIssue({ code: 'custom', message: `a ${record.subtype} needs its ${needed}` });
    }
  });

export type InterchangeAnnotation = z.infer<typeof interchangeAnnotationSchema>;

export const ANNOTATION_DATA_JSON_MARKER = 'monstera-annotations';
export const ANNOTATION_DATA_JSON_VERSION = 1;

/* -------------------------------------------------------------------- read */

/**
 * Every exchangeable annotation in the document, in page order and each page's walk order.
 *
 * An annotation whose entries do not make a record — a subtype outside the set, a highlight with
 * no quadrilaterals — is left out rather than written half-described.
 */
export function readInterchangeAnnotations(session: MupdfSession): Promise<readonly InterchangeAnnotation[]> {
  return withDocument(session, (document) => {
    const found: InterchangeAnnotation[] = [];
    const pages = document.countPages();
    for (let page = 0; page < pages; page += 1) {
      for (const annotation of document.loadPage(page).getAnnotations()) {
        const record = tolerantRecord(candidateFrom(annotation.getObject(), page));
        if (record !== null) found.push(record);
      }
    }
    return found;
  });
}

/**
 * The interchange records for SPECIFIC annotations, named by their walk handles — what a copy
 * reads before a paste writes it back through the one importer.
 *
 * ## Keyed by walk index, and never by position in {@link readInterchangeAnnotations}' answer
 *
 * That reader leaves out every annotation whose entries do not make a record, so its N-th entry
 * is not the walk's N-th annotation on any page carrying a subtype outside the set. A copy keyed
 * by position there would copy the NEXT mark whenever an unsupported one came before it — and
 * agree with the walk on every document where nothing is left out, which is how that ships.
 *
 * So the handle resolves through `annotationAt`, the walk's own resolver, and the record through
 * {@link candidateFrom} and {@link tolerantRecord}, the one reader of entries. Nothing here is a
 * second opinion about either question.
 *
 * ## `null` for a mark that makes no record, in its place
 *
 * The answer is positional against `indices`, so a caller can say WHICH of the marks it asked
 * about cannot be copied — a sticky note beside a stamp this build does not exchange — rather
 * than receiving a shorter list it has to line up by guesswork.
 */
export function readInterchangeRecordsAt(
  session: MupdfSession,
  page: number,
  indices: readonly number[],
): Promise<readonly (InterchangeAnnotation | null)[]> {
  return withDocument(session, (document) => {
    const loaded = pageAt(document, page, document.countPages());
    return indices.map((index) => tolerantRecord(candidateFrom(annotationAt(loaded, index).getObject(), page)));
  });
}

/**
 * What the clipboard's copy carries out of the host: the copyable records, already serialised in
 * this module's own JSON, and which of the asked-for marks made it in.
 *
 * ## Serialised HERE, because main may not load this module
 *
 * Main holds the clipboard, and this module imports MuPDF at its top — so main importing it would
 * load the engine into the process ADR-0026 keeps it out of. Main spelling the JSON by hand would
 * be a second writer of a format {@link serialiseAnnotationData} owns (B3a), agreeing with it until
 * either changes. So the host serialises, main keeps the TEXT without reading it, and a paste
 * encodes that text back into the bytes `importAnnotations` takes. UTF-8 encoding is not an
 * opinion about the format.
 *
 * `json` is the empty string when nothing asked for is exchangeable, rather than a file holding no
 * annotations: a paste of that would be refused by the importer, and the clipboard should not hold
 * something that can only fail.
 */
export async function copyAnnotationData(
  session: MupdfSession,
  page: number,
  indices: readonly number[],
): Promise<{ readonly json: string; readonly copyable: readonly boolean[] }> {
  const records = await readInterchangeRecordsAt(session, page, indices);
  const kept = records.filter((record): record is InterchangeAnnotation => record !== null);
  return {
    json: kept.length === 0 ? '' : new TextDecoder().decode(serialiseAnnotationData(kept, 'json')),
    copyable: records.map((record) => record !== null),
  };
}

/**
 * One annotation dictionary's entries as a candidate record, unchecked.
 *
 * THE ONE READER OF ENTRIES, taken by the document walk and by an FDF's `/Annots` alike, so a
 * file and a document cannot disagree about what `/C` means (B3a). What differs is what each does
 * with a candidate the schema refuses: {@link tolerantRecord} for the document, a refusal for a file.
 */
function candidateFrom(dictionary: PDFObject, page: number): Candidate {
  const subtype = nameIn(dictionary.get('Subtype'));
  const rect = numbersIn(dictionary.get('Rect'));
  // CHECKED BEFORE THE SECOND `get`: an absent `/BS` reads as MuPDF's shared null, which belongs to
  // no document and throws when asked for a key.
  const style = dictionary.get('BS');
  const border = (style.isDictionary() ? numberIn(style.get('W')) : undefined) ?? numbersIn(dictionary.get('Border'))?.[2];
  const endings = namesIn(dictionary.get('LE'));
  const ink = dictionary.get('InkList');
  const strokes: number[][] = [];
  if (ink.isArray()) {
    for (let index = 0; index < ink.length; index += 1) {
      const stroke = numbersIn(ink.get(index));
      if (stroke !== undefined) strokes.push(stroke);
    }
  }
  return present({
    page,
    subtype,
    rect,
    colour: numbersIn(dictionary.get('C')),
    interiorColour: numbersIn(dictionary.get('IC')),
    opacity: numberIn(dictionary.get('CA')),
    borderWidth: border,
    contents: textIn(dictionary.get('Contents')),
    author: textIn(dictionary.get('T')),
    subject: textIn(dictionary.get('Subj')),
    modified: textIn(dictionary.get('M')),
    quadPoints: numbersIn(dictionary.get('QuadPoints')),
    inkList: strokes.length > 0 ? strokes : undefined,
    vertices: numbersIn(dictionary.get('Vertices')),
    line: numbersIn(dictionary.get('L')),
    lineEndings: endings?.length === 2 ? endings : undefined,
    icon: subtype === 'Text' ? nameIn(dictionary.get('Name')) : undefined,
    defaultAppearance: subtype === 'FreeText' ? textIn(dictionary.get('DA')) : undefined,
  });
}

/** A record before the schema has seen it: every entry of the record's, each of unknown shape. */
type Candidate = { -readonly [K in keyof InterchangeAnnotation]?: unknown };

/** The candidate's entries that are there — an absent entry is no key, as in the dictionary. */
function present(candidate: Candidate): Candidate {
  const kept: Candidate = {};
  for (const [key, value] of Object.entries(candidate)) {
    if (value !== undefined) Object.assign(kept, { [key]: value });
  }
  return kept;
}

/**
 * A document's own annotation as a record, or `null` where it is not one.
 *
 * AN ENTRY THE SCHEMA REFUSES IS DROPPED BEFORE THE RECORD IS: a document's own date in a format
 * the schema does not accept should not cost the annotation on export. Only the optional entries
 * are retried; a record still refused is not exchangeable.
 */
function tolerantRecord(candidate: Candidate): InterchangeAnnotation | null {
  const parsed = interchangeAnnotationSchema.safeParse(candidate);
  if (parsed.success) return parsed.data;
  const kept: Candidate = { page: candidate.page, subtype: candidate.subtype, rect: candidate.rect };
  for (const [key, value] of Object.entries(candidate)) {
    if (key in kept || value === undefined) continue;
    const trial = interchangeAnnotationSchema.safeParse({ ...kept, [key]: value });
    const issues = trial.success ? [] : trial.error.issues.filter((issue) => issue.path[0] === key);
    if (issues.length === 0) Object.assign(kept, { [key]: value });
  }
  const retried = interchangeAnnotationSchema.safeParse(kept);
  return retried.success ? retried.data : null;
}

/**
 * A PDF number as MuPDF holds it, at the precision it holds it: a real is a C `float`, so `0.2`
 * written and read back is `0.20000000298023224` (measured 2026-09-17). Seven significant digits
 * is what a `float` carries, so the value is given at that — `0.2` stays `0.2`, and a record read
 * from a document and from its own export agree.
 */
function engineNumber(value: PDFObject): number {
  return Number(Math.fround(value.asNumber()).toPrecision(7));
}

function numberIn(value: PDFObject): number | undefined {
  return value.isNumber() ? engineNumber(value) : undefined;
}

function numbersIn(value: PDFObject): number[] | undefined {
  if (!value.isArray()) return undefined;
  const out: number[] = [];
  for (let index = 0; index < value.length; index += 1) {
    const entry = value.get(index);
    if (!entry.isNumber()) return undefined;
    out.push(engineNumber(entry));
  }
  return out;
}

function namesIn(value: PDFObject): string[] | undefined {
  if (!value.isArray()) return undefined;
  const out: string[] = [];
  for (let index = 0; index < value.length; index += 1) {
    const entry = value.get(index);
    if (!entry.isName()) return undefined;
    out.push(entry.asName());
  }
  return out;
}

function nameIn(value: PDFObject): string | undefined {
  return value.isName() ? value.asName() : undefined;
}

function textIn(value: PDFObject): string | undefined {
  return value.isString() ? value.asString() : undefined;
}

/* ------------------------------------------------------------------ export */

/** A value a format cannot carry, named, so the person can choose one that can. */
export class UnrepresentableAnnotationDataError extends Error {
  constructor(page: number) {
    super(
      `An annotation on page ${String(page + 1)} holds a character XML cannot carry, which XFDF has ` +
        'no escape for. Export as JSON or FDF, which carry it unchanged.',
    );
    this.name = 'UnrepresentableAnnotationDataError';
  }
}

/** The three encoders, as UTF-8 bytes. `serialiseFormData`'s shape. */
export function serialiseAnnotationData(
  records: readonly InterchangeAnnotation[],
  format: AnnotationDataFormat,
): Uint8Array {
  if (format === 'json') {
    return new TextEncoder().encode(
      `${JSON.stringify(
        { format: ANNOTATION_DATA_JSON_MARKER, version: ANNOTATION_DATA_JSON_VERSION, annotations: records },
        null,
        2,
      )}\n`,
    );
  }
  if (format === 'xfdf') return new TextEncoder().encode(xfdfAnnotations(records));
  return new TextEncoder().encode(fdfAnnotations(records));
}

/** XFDF's element for each subtype, and back. */
const XFDF_ELEMENTS: Readonly<Record<InterchangeSubtype, string>> = {
  Text: 'text',
  FreeText: 'freetext',
  Line: 'line',
  Square: 'square',
  Circle: 'circle',
  Polygon: 'polygon',
  PolyLine: 'polyline',
  Highlight: 'highlight',
  Underline: 'underline',
  Squiggly: 'squiggly',
  StrikeOut: 'strikeout',
  Caret: 'caret',
  Ink: 'ink',
  Redact: 'redact',
};

/** A number as the text formats write it: four decimal places at most, no trailing zeros. */
function written(value: number): string {
  return String(Number(value.toFixed(4)));
}

function pairs(numbers: readonly number[]): string {
  const out: string[] = [];
  for (let index = 0; index + 1 < numbers.length; index += 2) {
    out.push(`${written(numbers[index] ?? 0)},${written(numbers[index + 1] ?? 0)}`);
  }
  return out.join(';');
}

/**
 * XFDF's colour: `#RRGGBB`. A grey is written as its RGB; a CMYK colour is converted, which is the
 * one entry XFDF cannot carry exactly and the reason JSON and FDF write the components.
 */
function hexColour(components: readonly number[]): string | undefined {
  let rgb: readonly number[];
  if (components.length === 1) rgb = [components[0] ?? 0, components[0] ?? 0, components[0] ?? 0];
  else if (components.length === 3) rgb = components;
  else if (components.length === 4) {
    const [c = 0, m = 0, y = 0, k = 0] = components;
    rgb = [(1 - c) * (1 - k), (1 - m) * (1 - k), (1 - y) * (1 - k)];
  } else return undefined;
  return `#${rgb.map((value) => Math.round(value * 255).toString(16).toUpperCase().padStart(2, '0')).join('')}`;
}

function xfdfAnnotations(records: readonly InterchangeAnnotation[]): string {
  const lines = [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<xfdf xmlns="http://ns.adobe.com/xfdf/" xml:space="preserve">',
    '  <annots>',
  ];
  for (const record of records) {
    const texts = [record.contents, record.author, record.subject, record.defaultAppearance];
    if (!texts.every((text) => text === undefined || xmlCanCarry(text))) {
      throw new UnrepresentableAnnotationDataError(record.page);
    }
    const attributes: [string, string | undefined][] = [
      ['page', String(record.page)],
      ['rect', record.rect.map(written).join(',')],
      ['color', record.colour === undefined ? undefined : hexColour(record.colour)],
      ['interior-color', record.interiorColour === undefined ? undefined : hexColour(record.interiorColour)],
      ['opacity', record.opacity === undefined ? undefined : written(record.opacity)],
      ['width', record.borderWidth === undefined ? undefined : written(record.borderWidth)],
      ['title', record.author],
      ['subject', record.subject],
      ['date', record.modified],
      ['icon', record.icon],
      ['coords', record.quadPoints?.map(written).join(',')],
      ['vertices', record.vertices === undefined ? undefined : pairs(record.vertices)],
      ['start', record.line === undefined ? undefined : pairs(record.line.slice(0, 2))],
      ['end', record.line === undefined ? undefined : pairs(record.line.slice(2, 4))],
      ['head', record.lineEndings?.[0]],
      ['tail', record.lineEndings?.[1]],
    ];
    const spelt = attributes
      .filter((entry): entry is [string, string] => entry[1] !== undefined)
      .map(([name, value]) => ` ${name}="${xmlEscaped(value)}"`)
      .join('');
    const children: string[] = [];
    if (record.contents !== undefined) children.push(`<contents>${xmlEscaped(record.contents)}</contents>`);
    if (record.inkList !== undefined) {
      children.push(`<inklist>${record.inkList.map((stroke) => `<gesture>${pairs(stroke)}</gesture>`).join('')}</inklist>`);
    }
    if (record.defaultAppearance !== undefined) {
      children.push(`<defaultappearance>${xmlEscaped(record.defaultAppearance)}</defaultappearance>`);
    }
    const element = XFDF_ELEMENTS[record.subtype];
    lines.push(
      children.length === 0
        ? `    <${element}${spelt}/>`
        : `    <${element}${spelt}>${children.join('')}</${element}>`,
    );
  }
  lines.push('  </annots>', '</xfdf>', '');
  return lines.join('\n');
}

function fdfNumbers(numbers: readonly number[]): string {
  return `[${numbers.map(written).join(' ')}]`;
}

function fdfAnnotations(records: readonly InterchangeAnnotation[]): string {
  return fdfFile([
    '<< /FDF << /Annots 2 0 R >> >>',
    `[ ${records.map((_record, index) => `${String(index + 3)} 0 R`).join(' ')} ]`,
    ...records.map((record) => {
      const entries = [
        '/Type /Annot',
        `/Subtype ${pdfName(record.subtype)}`,
        `/Page ${String(record.page)}`,
        `/Rect ${fdfNumbers(record.rect)}`,
      ];
      if (record.colour !== undefined) entries.push(`/C ${fdfNumbers(record.colour)}`);
      if (record.interiorColour !== undefined) entries.push(`/IC ${fdfNumbers(record.interiorColour)}`);
      if (record.opacity !== undefined) entries.push(`/CA ${written(record.opacity)}`);
      if (record.borderWidth !== undefined) entries.push(`/BS << /W ${written(record.borderWidth)} >>`);
      if (record.contents !== undefined) entries.push(`/Contents ${pdfString(record.contents)}`);
      if (record.author !== undefined) entries.push(`/T ${pdfString(record.author)}`);
      if (record.subject !== undefined) entries.push(`/Subj ${pdfString(record.subject)}`);
      if (record.modified !== undefined) entries.push(`/M ${pdfString(record.modified)}`);
      if (record.quadPoints !== undefined) entries.push(`/QuadPoints ${fdfNumbers(record.quadPoints)}`);
      if (record.inkList !== undefined) entries.push(`/InkList [${record.inkList.map(fdfNumbers).join(' ')}]`);
      if (record.vertices !== undefined) entries.push(`/Vertices ${fdfNumbers(record.vertices)}`);
      if (record.line !== undefined) entries.push(`/L ${fdfNumbers(record.line)}`);
      if (record.lineEndings !== undefined) entries.push(`/LE [${record.lineEndings.map(pdfName).join(' ')}]`);
      if (record.icon !== undefined) entries.push(`/Name ${pdfName(record.icon)}`);
      if (record.defaultAppearance !== undefined) entries.push(`/DA ${pdfString(record.defaultAppearance)}`);
      return `<< ${entries.join(' ')} >>`;
    }),
  ]);
}

/* ------------------------------------------------------------------ import */

/** A file that is not annotation data this build reads, with the reason it was refused. */
export class UnreadableAnnotationDataError extends Error {
  constructor(detail: string) {
    super(`This annotation file was refused: ${detail}.`);
    this.name = 'UnreadableAnnotationDataError';
  }
}

/** A file that parsed and carries no annotation this build exchanges — the wrong file, most likely. */
export class NoImportableAnnotationsError extends Error {
  constructor() {
    super('The file carries no annotation this build imports, so nothing was added.');
    this.name = 'NoImportableAnnotationsError';
  }
}

/** A record naming a page this document does not have. Refused whole, like a form value. */
export class AnnotationPageMissingError extends Error {
  constructor(page: number, pages: number) {
    super(
      `The file places an annotation on page ${String(page + 1)} and this document has ${String(pages)}. ` +
        'Nothing was added: importing the rest would leave that one out with no report.',
    );
    this.name = 'AnnotationPageMissingError';
  }
}

/**
 * What an annotation file says, whichever format it is in, every record checked by the one schema.
 *
 * A record the schema refuses refuses the file: the import is one command, and adding the
 * annotations that happened to be well-formed would leave the rest out with no report.
 */
export function parseAnnotationData(bytes: Uint8Array, format: AnnotationDataFormat): readonly InterchangeAnnotation[] {
  if (format === 'fdf') return parseFdf(bytes);
  let text: string;
  try {
    text = new TextDecoder('utf-8', { fatal: true }).decode(bytes);
  } catch (error) {
    throw new UnreadableAnnotationDataError(error instanceof Error ? error.message : String(error));
  }
  const candidates = format === 'json' ? jsonCandidates(text) : readXfdfAnnotations(text).flatMap(xfdfCandidate);
  if (candidates.length > MAX_INTERCHANGE_ANNOTATIONS) {
    throw new UnreadableAnnotationDataError(`it carries more than ${String(MAX_INTERCHANGE_ANNOTATIONS)} annotations`);
  }
  return candidates.map((candidate, index) => checked(candidate, index));
}

function checked(candidate: unknown, index: number): InterchangeAnnotation {
  const parsed = interchangeAnnotationSchema.safeParse(candidate);
  if (!parsed.success) {
    const issue = parsed.error.issues[0];
    throw new UnreadableAnnotationDataError(
      `annotation ${String(index + 1)} ${issue === undefined ? 'is malformed' : `— ${issue.path.join('.')}: ${issue.message}`}`,
    );
  }
  return parsed.data;
}

const jsonFileSchema = z
  .object({
    format: z.literal(ANNOTATION_DATA_JSON_MARKER),
    version: z.literal(ANNOTATION_DATA_JSON_VERSION),
    annotations: z.array(z.unknown()).max(MAX_INTERCHANGE_ANNOTATIONS),
  })
  .strict();

function jsonCandidates(text: string): readonly unknown[] {
  let decoded: unknown;
  try {
    decoded = JSON.parse(text);
  } catch (error) {
    throw new UnreadableAnnotationDataError(error instanceof Error ? error.message : String(error));
  }
  const parsed = jsonFileSchema.safeParse(decoded);
  if (!parsed.success) {
    throw new UnreadableAnnotationDataError("it is JSON, but not this build's annotation data");
  }
  return parsed.data.annotations;
}

const SUBTYPE_OF_ELEMENT = new Map<string, InterchangeSubtype>(
  INTERCHANGE_SUBTYPES.map((subtype) => [XFDF_ELEMENTS[subtype], subtype]),
);

/** Numbers in an attribute, separated by commas, semicolons or spaces; any other text refuses. */
function numbersOf(text: string, what: string): number[] {
  const parts = text.trim().split(/[\s,;]+/u).filter((part) => part !== '');
  return parts.map((part) => {
    const value = Number(part);
    if (!Number.isFinite(value)) throw new UnreadableAnnotationDataError(`${what} holds "${part.slice(0, 32)}", which is not a number`);
    return value;
  });
}

function colourOf(text: string): number[] {
  const match = /^#([0-9a-fA-F]{2})([0-9a-fA-F]{2})([0-9a-fA-F]{2})$/u.exec(text.trim());
  if (match === null) throw new UnreadableAnnotationDataError(`a colour "${text.slice(0, 32)}" is not #RRGGBB`);
  return [match[1], match[2], match[3]].map((hex) => Number.parseInt(hex ?? '0', 16) / 255);
}

/**
 * One XFDF element as a candidate record — or none, for an element this build does not exchange
 * (a `<fileattachment>`, a `<sound>`), which a foreign file may carry beside the ones it does.
 */
function xfdfCandidate(element: XfdfAnnotation): unknown[] {
  const subtype = SUBTYPE_OF_ELEMENT.get(element.element);
  if (subtype === undefined) return [];
  const get = (name: string): string | undefined => element.attributes.get(name);
  const candidate: Candidate = {
    page: Number(get('page')),
    subtype,
    rect: numbersOf(get('rect') ?? '', 'rect'),
  };
  const colourText = get('color');
  if (colourText !== undefined) candidate.colour = colourOf(colourText);
  const interior = get('interior-color');
  if (interior !== undefined) candidate.interiorColour = colourOf(interior);
  const opacity = get('opacity');
  if (opacity !== undefined) candidate.opacity = Number(opacity);
  const width = get('width');
  if (width !== undefined) candidate.borderWidth = Number(width);
  // THE PLAIN TEXT WHEN THERE IS ONE, and otherwise the rich text's words — a note from Acrobat or
  // PDF-XChange may carry only the rich form, and dropping it lost the note's whole text.
  if (element.contents !== undefined) candidate.contents = element.contents;
  else if (element.richText !== undefined && element.richText !== '') candidate.contents = element.richText;
  const title = get('title');
  if (title !== undefined) candidate.author = title;
  const subject = get('subject');
  if (subject !== undefined) candidate.subject = subject;
  const date = get('date');
  if (date !== undefined) candidate.modified = date;
  const icon = get('icon');
  if (icon !== undefined) candidate.icon = icon;
  const coords = get('coords');
  if (coords !== undefined) candidate.quadPoints = numbersOf(coords, 'coords');
  const vertices = get('vertices');
  if (vertices !== undefined) candidate.vertices = numbersOf(vertices, 'vertices');
  const start = get('start');
  const end = get('end');
  if (start !== undefined && end !== undefined) {
    candidate.line = [...numbersOf(start, 'start'), ...numbersOf(end, 'end')];
  }
  const head = get('head');
  const tail = get('tail');
  if (head !== undefined || tail !== undefined) candidate.lineEndings = [head ?? 'None', tail ?? 'None'];
  if (element.gestures.length > 0) {
    candidate.inkList = element.gestures.map((gesture) => numbersOf(gesture, 'a gesture'));
  }
  if (element.defaultAppearance !== undefined) candidate.defaultAppearance = element.defaultAppearance;
  return [candidate];
}

/**
 * An FDF's `/Annots`, read by the same entry reader the document walk uses.
 *
 * MuPDF declares no FDF API, so the bytes open as a document under the FDF type — `parseFormData`'s
 * route. `/Page` is the FDF's own entry; a dictionary without one is refused, because guessing a
 * page would put a note somewhere its author did not.
 */
function parseFdf(bytes: Uint8Array): readonly InterchangeAnnotation[] {
  let document: mupdf.Document;
  try {
    document = mupdf.PDFDocument.openDocument(bytes, 'application/vnd.fdf');
  } catch (error) {
    throw new UnreadableAnnotationDataError(error instanceof Error ? error.message : String(error));
  }
  if (!(document instanceof mupdf.PDFDocument)) {
    throw new UnreadableAnnotationDataError('it opened as something that is not PDF syntax');
  }
  try {
    const list = document.getTrailer().get('Root').get('FDF').get('Annots');
    if (!list.isArray()) throw new UnreadableAnnotationDataError('it has no /Root /FDF /Annots array');
    if (list.length > MAX_INTERCHANGE_ANNOTATIONS) {
      throw new UnreadableAnnotationDataError(`it carries more than ${String(MAX_INTERCHANGE_ANNOTATIONS)} annotations`);
    }
    const found: InterchangeAnnotation[] = [];
    for (let index = 0; index < list.length; index += 1) {
      const entry = list.get(index);
      if (!entry.isDictionary()) continue;
      const subtype = nameIn(entry.get('Subtype'));
      if (subtype === undefined || !(INTERCHANGE_SUBTYPES as readonly string[]).includes(subtype)) continue;
      const page = numberIn(entry.get('Page'));
      if (page === undefined) {
        throw new UnreadableAnnotationDataError(`annotation ${String(index + 1)} names no /Page`);
      }
      found.push(checked(candidateFrom(entry, page), index));
    }
    return found;
  } finally {
    document.destroy();
  }
}

/* ------------------------------------------------------------------- apply */

/**
 * Adds every annotation the file carries, or none.
 *
 * Every record is parsed and every page checked before the first is created, so a file naming a
 * page this document lacks changes nothing. Each annotation is created by MuPDF for its subtype,
 * given its entries raw in user space, marked as this build's, and drawn by `update()`.
 */
/**
 * How far a record pasted onto its own page moves, in PDF points — right and down.
 *
 * A copy written exactly over its original is invisible, and a person who cannot see a paste runs
 * it again. Twelve points is one step of a typical 12-point line: far enough to read as a second
 * mark, near enough to read as a copy OF that mark.
 */
const PASTE_NUDGE = 12;

/**
 * A record moved to the page a paste names, and nudged when the paste says so.
 *
 * WHETHER to nudge is the caller's, not inferred here: a record names a page and not a document,
 * so `record.page === paste.page` cannot tell *pasted back onto its own page* from *pasted onto
 * the same page number of another file* — and the first version, which inferred it, nudged the
 * second. See `importAnnotationsSchema.paste`.
 *
 * EVERY coordinate the record carries moves together — the box, and the geometry the subtype is
 * drawn from. Moving the box alone would leave a highlight's quadrilaterals, an ink stroke or a
 * polygon where the original is while its rectangle sits somewhere else, which MuPDF would draw
 * as a mark clipped to the wrong place.
 */
function retargeted(
  record: InterchangeAnnotation,
  paste: { readonly page: number; readonly nudge: boolean } | undefined,
): InterchangeAnnotation {
  if (paste === undefined) return record;
  const onPage = paste.page;
  if (!paste.nudge) return { ...record, page: onPage };
  // PDF USER SPACE: y grows upward, so "down" is a subtraction.
  const pairs = (numbers: readonly number[]): number[] =>
    numbers.map((value, at) => (at % 2 === 0 ? value + PASTE_NUDGE : value - PASTE_NUDGE));
  const [x0, y0, x1, y1] = record.rect;
  return {
    ...record,
    page: onPage,
    rect: [x0 + PASTE_NUDGE, y0 - PASTE_NUDGE, x1 + PASTE_NUDGE, y1 - PASTE_NUDGE],
    ...(record.quadPoints === undefined ? {} : { quadPoints: pairs(record.quadPoints) }),
    ...(record.inkList === undefined ? {} : { inkList: record.inkList.map(pairs) }),
    ...(record.vertices === undefined ? {} : { vertices: pairs(record.vertices) }),
    ...(record.line === undefined ? {} : { line: nudgedLine(record.line) }),
  };
}

/** A line's two ends moved by the paste nudge, kept a four-tuple rather than cast back to one. */
function nudgedLine(line: readonly [number, number, number, number]): [number, number, number, number] {
  const [ax, ay, bx, by] = line;
  return [ax + PASTE_NUDGE, ay - PASTE_NUDGE, bx + PASTE_NUDGE, by - PASTE_NUDGE];
}

export const applyImportAnnotations: Apply<'mupdf', 'importAnnotations'> = (session, command) =>
  withDocument(session, (document) => {
    const records = parseAnnotationData(command.bytes, command.format).map((record) =>
      retargeted(record, command.paste),
    );
    if (records.length === 0) throw new NoImportableAnnotationsError();
    const pages = document.countPages();
    for (const record of records) {
      if (record.page >= pages) throw new AnnotationPageMissingError(record.page, pages);
    }
    for (const record of records) {
      const annotation = document.loadPage(record.page).createAnnotation(record.subtype);
      writeEntries(document, annotation.getObject(), record);
      markAuthored(annotation);
      // DRAWN NOW, and not load-bearing for the file: measured 2026-09-17, with this call removed
      // MuPDF's save still wrote a correct appearance (`7 w`, `1 0 0 RG`, the inset box) for an
      // imported square. It is MuPDF's own call for an annotation whose entries changed, and it
      // gives the session an appearance before any save does. Through `redraw`, the kernel's one
      // redraw, so an imported `/BM` reaches the appearance too (ADR-0103).
      redraw(annotation, document);
    }
  });

function realArray(document: PDFDocument, numbers: readonly number[]): PDFObject {
  const array = document.newArray();
  for (const value of numbers) array.push(document.newReal(value));
  return array;
}

/**
 * The subtypes whose `/C` is the colour of their STROKE — a border or a line — so an absent `/C`
 * means that stroke is not drawn (PDF 32000-1, 12.5.6.8–12.5.6.13). A record without a colour for
 * one of these keeps it absent. The rest — a note's icon, text markup, a text box — are drawn in
 * a viewer's default when `/C` is absent, and keep the colour MuPDF gives a new annotation.
 */
const STROKE_COLOURED: ReadonlySet<InterchangeSubtype> = new Set(['Square', 'Circle', 'Line', 'Polygon', 'PolyLine', 'Ink']);

/**
 * The record's entries, onto a dictionary MuPDF just created. Every entry the record lacks is left
 * as MuPDF made it, EXCEPT a stroke colour (above): MuPDF gives a new square a red border, and an
 * area highlight from PDF-XChange — a fill with no `/C` and a zero-width border — arrived outlined
 * in red that its author never drew (measured 2026-09-21).
 */
function writeEntries(document: PDFDocument, dictionary: PDFObject, record: InterchangeAnnotation): void {
  dictionary.put('Rect', realArray(document, record.rect));
  if (record.colour !== undefined) dictionary.put('C', realArray(document, record.colour));
  else if (STROKE_COLOURED.has(record.subtype)) dictionary.delete('C');
  if (record.interiorColour !== undefined) dictionary.put('IC', realArray(document, record.interiorColour));
  if (record.opacity !== undefined) dictionary.put('CA', document.newReal(record.opacity));
  if (record.borderWidth !== undefined) {
    const style = document.newDictionary();
    style.put('W', document.newReal(record.borderWidth));
    dictionary.put('BS', style);
  }
  if (record.contents !== undefined) dictionary.put('Contents', document.newString(record.contents));
  if (record.author !== undefined) dictionary.put('T', document.newString(record.author));
  if (record.subject !== undefined) dictionary.put('Subj', document.newString(record.subject));
  if (record.modified !== undefined) dictionary.put('M', document.newString(record.modified));
  if (record.quadPoints !== undefined) dictionary.put('QuadPoints', realArray(document, record.quadPoints));
  if (record.inkList !== undefined) {
    const strokes = document.newArray();
    for (const stroke of record.inkList) strokes.push(realArray(document, stroke));
    dictionary.put('InkList', strokes);
  }
  if (record.vertices !== undefined) dictionary.put('Vertices', realArray(document, record.vertices));
  if (record.line !== undefined) dictionary.put('L', realArray(document, record.line));
  if (record.lineEndings !== undefined) {
    const endings = document.newArray();
    for (const ending of record.lineEndings) endings.push(document.newName(ending));
    dictionary.put('LE', endings);
  }
  if (record.icon !== undefined) dictionary.put('Name', document.newName(record.icon));
  if (record.defaultAppearance !== undefined) dictionary.put('DA', document.newString(record.defaultAppearance));
}

/**
 * An import records no prior state, for `captureImportFormData`'s reason: what it adds is decided
 * by a file the command has not parsed yet, and the checkpoint restores the document exactly.
 */
export function captureImportAnnotations(): Promise<CaptureResult<never>> {
  return Promise.resolve({
    captured: false,
    reason:
      'an import adds whatever annotations the file carries, which the command cannot know before ' +
      'it parses — the checkpoint restores the document exactly',
  });
}

/** Unreachable, and required by `CommandSpec`'s shape — `invertImportFormData`'s reason. */
export const invertImportAnnotations: Invert<'mupdf', 'importAnnotations'> = (): Promise<void> => {
  throw new Error('imported annotations have no inverse; undo restores the checkpoint the bus took (ADR-0037)');
};
