import { Font, type PDFAnnotation, type PDFDocument, type PDFObject } from './mupdfRaw.js';
import { lookOfStyleString, normalisedRuns, richTextOf, runsOfRichText, styleStringOf } from './textBoxRichText.js';
import {
  type BoxAlign,
  type BoxLook,
  type Face,
  type Measure,
  type Rgb,
  type TextRun,
  DEFAULT_LOOK,
  MAX_LINE_HEIGHT,
  MAX_PADDING,
  MIN_LINE_HEIGHT,
  appearanceContent,
  faceNames,
  layoutBox,
} from './textBoxStyle.js';

/**
 * The engine's half of a styled text box
 * ([ADR-0211](../../../docs/DECISIONS/0211-a-text-box-with-styled-words-has-an-appearance-monstera-writes-itself.md)): what is
 * stored on the annotation, and the appearance written from it.
 *
 * ## Four facts, and the appearance is a function of them
 *
 * `/Contents` (the plain words, unchanged: search, the panel and every reader that ignores the rest still have them), `/RC`
 * (the styled runs), `/DS` (the box's own style), and `/IC` (the fill; the margin is `/DS`'s). {@link drawStyledAppearance}
 * reads them and writes `/AP /N`; nothing else does, so what a reader that draws `/AP` shows and what a reader that draws
 * `/RC` shows are one thing said twice (B3).
 *
 * ## Only a box carrying `/MonsteraStyle` is touched
 *
 * A foreign FreeText with its own `/RC` is KEPT (Decision 4): its appearance is regenerated by the engine as it always was,
 * and its rich text is not rewritten. The marker is private and harmless to every other reader.
 *
 * ## Where it runs
 *
 * After MuPDF has drawn: {@link redraw}'s one finishing step, because MuPDF regenerates `/AP` from `/Contents` and `/DA` at
 * every redraw and a replaced stream does not survive it (measured 2026-10-08, 1.28.0).
 */

/** The private key that says Monstera wrote this box's style. */
export const STYLE_MARKER = 'MonsteraStyle';

/** MuPDF's own face names for `Face`, which is also what the base 14's `/BaseFont` is. */
const faces = new Map<Face, Font>();

function fontOf(face: Face): Font {
  let held = faces.get(face);
  if (held === undefined) {
    held = new Font(face);
    faces.set(face, held);
  }
  return held;
}

/** A word's width from the engine's own copy of the base 14, whose widths are the format's (AFM-compatible). No kerning. */
export const engineMeasure: Measure = (face, text, size) => {
  const font = fontOf(face);
  let advance = 0;
  for (const character of text) advance += font.advanceGlyph(font.encodeCharacter(character.codePointAt(0) ?? 0x20));
  return advance * size;
};

/** The text-box and typewriter FreeTexts, which this writer draws; a callout's leader is the engine's. */
export function isStylable(annotation: PDFAnnotation): boolean {
  if (annotation.getType() !== 'FreeText') return false;
  const intent = annotation.getObject().get('IT');
  return !intent.isName() || intent.asName() === 'FreeTextTypeWriter';
}

/** Whether Monstera wrote this box's style. */
export function isStyled(annotation: PDFAnnotation): boolean {
  return annotation.getType() === 'FreeText' && annotation.getObject().get(STYLE_MARKER).isBoolean();
}

const ALIGN_OF_Q: readonly BoxAlign[] = ['left', 'center', 'right'];
const Q_OF_ALIGN: Readonly<Record<BoxAlign, number>> = { left: 0, center: 1, right: 2, justify: 0 };

function rgbOf(array: PDFObject): Rgb | null {
  if (!array.isArray() || array.length !== 3) return null;
  return [array.get(0).asNumber(), array.get(1).asNumber(), array.get(2).asNumber()];
}

/** The look a box stands with, from `/DS` read over `/DA`, `/Q`, `/IC` and `/BS`; and its runs. */
export function readStyledBox(annotation: PDFAnnotation): { readonly look: BoxLook; readonly runs: readonly TextRun[] } {
  const object = annotation.getObject();
  const da = annotation.getDefaultAppearance();
  const base: BoxLook = {
    ...DEFAULT_LOOK,
    size: da.size > 0 ? da.size : DEFAULT_LOOK.size,
    colour: da.color.length === 3 ? [da.color[0], da.color[1], da.color[2]] : DEFAULT_LOOK.colour,
    align: ALIGN_OF_Q[annotation.getQuadding()] ?? 'left',
    fill: rgbOf(object.get('IC')),
    borderWidth: annotation.hasBorder() ? annotation.getBorderWidth() : 0,
  };
  const ds = object.get('DS');
  const styled = ds.isString() ? lookOfStyleString(ds.asString(), base) : base;
  const look: BoxLook = { ...styled, borderColour: styled.colour };
  const contents = annotation.getContents();
  const rc = object.get('RC');
  const fromRich = rc.isString() || rc.isStream() ? runsOfRichText(rc.isString() ? rc.asString() : rc.readStream().asString()) : undefined;
  // THE RUNS ARE USED ONLY WHILE THEY SAY WHAT /Contents SAYS: words edited by any other route leave the runs behind, and a
  // style drawn over words that are no longer there would show the OLD text.
  const joined = fromRich?.map((run) => run.text).join('') ?? '';
  const same = fromRich !== undefined && joined.replace(/\r\n|\r/gu, '\n') === contents.replace(/\r\n|\r/gu, '\n');
  return { look, runs: same ? fromRich : [{ text: contents }] };
}

/** A base-14 Type 1 font dictionary, WinAnsi: the same one every viewer carries. */
function fontDictionary(document: PDFDocument, face: Face): PDFObject {
  const dictionary = document.newDictionary();
  dictionary.put('Type', document.newName('Font'));
  dictionary.put('Subtype', document.newName('Type1'));
  dictionary.put('BaseFont', document.newName(face));
  dictionary.put('Encoding', document.newName('WinAnsiEncoding'));
  return dictionary;
}

/**
 * Writes `/AP /N` from the box's own four facts. **Answers `false` for a box it cannot draw** — a script outside WinAnsi, a
 * box with no room — and then writes nothing, so the engine's appearance stands with the plain words.
 */
export function drawStyledAppearance(annotation: PDFAnnotation, document: PDFDocument): boolean {
  const [x0, y0, x1, y1] = annotation.getRect();
  const { look, runs } = readStyledBox(annotation);
  const layout = layoutBox(x1 - x0, y1 - y0, look, runs, engineMeasure);
  if (layout === undefined) return false;
  const stream = document.newDictionary();
  stream.put('Type', document.newName('XObject'));
  stream.put('Subtype', document.newName('Form'));
  const box = document.newArray();
  for (const edge of [0, 0, x1 - x0, y1 - y0]) box.push(edge);
  stream.put('BBox', box);
  const resources = document.newDictionary();
  const fonts = document.newDictionary();
  for (const [face, name] of faceNames(layout)) fonts.put(name, fontDictionary(document, face));
  resources.put('Font', fonts);
  stream.put('Resources', resources);
  const made = document.addStream(appearanceContent(layout, look), stream);
  const appearances = annotation.getObject().get('AP');
  if (appearances.isDictionary()) appearances.put('N', made);
  else {
    const fresh = document.newDictionary();
    fresh.put('N', made);
    annotation.getObject().put('AP', fresh);
  }
  return true;
}

/**
 * What a restyle names: each field optional, an absent one left as the box has it. `words` replaces the runs; the others
 * change the box's own look.
 */
export interface StyledBoxChange {
  readonly family?: BoxLook['family'] | undefined;
  readonly size?: number | undefined;
  readonly colour?: Rgb | undefined;
  readonly bold?: boolean | undefined;
  readonly italic?: boolean | undefined;
  readonly underline?: boolean | undefined;
  readonly strike?: boolean | undefined;
  readonly align?: BoxAlign | undefined;
  readonly lineHeight?: number | undefined;
  /** `null` takes the fill away. */
  readonly fill?: Rgb | null | undefined;
  readonly padding?: number | undefined;
  readonly words?: readonly TextRun[] | undefined;
}

/**
 * Writes a change into the box's four facts and marks it. The appearance is NOT drawn here: the caller's redraw finishes it,
 * so a restyle and an edit of the words end the same way (B3).
 *
 * @param before what the box said BEFORE the caller touched its `/DA`: MuPDF's `setDefaultAppearance` deletes `/DS` (measured
 * 2026-10-08, 1.28.0), so a caller that sets the default appearance first reads a box that has lost its style.
 */
export function writeStyleFacts(
  annotation: PDFAnnotation,
  document: PDFDocument,
  change: StyledBoxChange,
  before?: ReturnType<typeof readStyledBox>,
): void {
  const object = annotation.getObject();
  const now = before ?? readStyledBox(annotation);
  const base = now.look;
  const clamp = (value: number, low: number, high: number): number => Math.min(high, Math.max(low, value));
  const look: BoxLook = {
    ...base,
    family: change.family ?? base.family,
    size: change.size ?? base.size,
    colour: change.colour ?? base.colour,
    bold: change.bold ?? base.bold,
    italic: change.italic ?? base.italic,
    underline: change.underline ?? base.underline,
    strike: change.strike ?? base.strike,
    align: change.align ?? base.align,
    lineHeight: clamp(change.lineHeight ?? base.lineHeight, MIN_LINE_HEIGHT, MAX_LINE_HEIGHT),
    fill: change.fill === undefined ? base.fill : change.fill,
    padding: clamp(change.padding ?? base.padding, 0, MAX_PADDING),
  };
  const runs = change.words === undefined ? now.runs : normalisedRuns(change.words);
  // THE PLAIN WORDS ARE THE RUNS JOINED, so a restyle that names words keeps `/Contents` and `/RC` one text.
  if (change.words !== undefined) annotation.setContents(runs.map((run) => run.text).join(''));
  object.put(STYLE_MARKER, true);
  object.put('DS', document.newString(styleStringOf(look)));
  object.put('RC', document.newString(richTextOf(runs, look)));
  annotation.setQuadding(Q_OF_ALIGN[look.align]);
  if (look.fill === null) object.delete('IC');
  else {
    const colour = document.newArray();
    for (const channel of look.fill) colour.push(channel);
    object.put('IC', colour);
  }
  // `/RD` is NOT written: see `styleStringOf` for why the margin is `/DS`'s.
}

/**
 * The finishing step of a redraw: a box Monstera styled gets its appearance written, over what MuPDF just drew. A box this
 * cannot draw is left as MuPDF drew it.
 */
export function restyled(annotation: PDFAnnotation, document: PDFDocument): void {
  if (!isStyled(annotation) || !isStylable(annotation)) return;
  drawStyledAppearance(annotation, document);
}
